Repository vinyldns/vinyldns, pull requests merged in 2019-07, with the labels that each got.

#737 Fix issue with sync button not appearing in portal
  modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
Labels: bug

#740 add errors to record owner group field
  modules/portal/app/views/batchChanges/batchChangeNew.scala.html
  modules/portal/public/css/vinyldns.css
  modules/portal/public/lib/batch-change/batch-change-new.controller.js
Labels: portal

#741 update group detail page
  modules/api/functional_test/live_tests/membership/list_group_members_test.py
  modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
  modules/portal/app/views/groups/groupDetail.scala.html
  modules/portal/public/lib/controllers/controller.membership.spec.js
Labels: portal

#738 make zone discovery case insensitive
  modules/api/functional_test/live_tests/batch/create_batch_change_test.py
  modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
  modules/api/src/test/scala/vinyldns/api/domain/batch/BatchTransformationsSpec.scala
Labels: bug

#742 allow updates to dotted CNAME records
  docker/bind9/zones/ok.hosts
  modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
  modules/api/functional_test/live_tests/recordsets/list_recordsets_test.py
  modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
  modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
  modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
  modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
Labels: bug

#747 Add Travis CI Slack integration
  .travis.yml
Labels: maintenance

#730 add backend ID info to docs
  modules/docs/src/main/tut/api/zone-model.md
  modules/docs/src/main/tut/operator/config-api.md
Labels: docs

#739 Properly reject requests sent to non-existent routes
  modules/api/functional_test/live_tests/authentication_test.py
  modules/api/functional_test/live_tests/membership/create_group_test.py
  modules/api/functional_test/live_tests/membership/update_group_test.py
  modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/JsonValidation.scala
  modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/VinylDNSDirectives.scala
  modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
  modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
  modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/VinylDNSDirectivesSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/VinylDNSRouteTestHelper.scala
  modules/api/src/test/scala/vinyldns/api/route/VinylDNSServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
  modules/core/src/main/scala/vinyldns/core/domain/membership/Group.scala
  scalastyle-config.xml
Labels: bug
