Repository vinyldns/vinyldns, pull requests merged in 2019-10, with the labels that each got.

#858 #261 Update cats-effect to 2.0.0 and fs2 to 2.0.1
  AUTHORS.md
  modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
  modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
  modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
  project/Dependencies.scala
Labels: external contribution, hacktoberfest

#855 Update README.md
  AUTHORS.md
  README.md
Labels: external contribution

#862 Add logging around sent notifications in the API
  modules/core/src/main/scala/vinyldns/core/notifier/AllNotifiers.scala
Labels: external contribution, hacktoberfest

#866 Rename batch change files to dns change
  modules/portal/app/controllers/FrontendController.scala
  modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
  modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
  modules/portal/app/views/dnsChanges/dnsChanges.scala.html
  modules/portal/conf/routes
  modules/portal/public/lib/dns-change/dns-change-detail.controller.js
  modules/portal/public/lib/dns-change/dns-change-new.controller.js
  modules/portal/public/lib/dns-change/dns-change.directive.js
  modules/portal/public/lib/dns-change/dns-change.module.js
  modules/portal/public/lib/dns-change/dns-change.service.js
  modules/portal/public/lib/dns-change/dns-change.spec.js
  modules/portal/public/lib/dns-change/dns-changes.controller.js
Labels: external contribution, hacktoberfest

#881 add license badge to Readme
  README.md
Labels: hacktoberfest

#882 remove empty record data fields from json
  modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
  modules/portal/public/lib/dns-change/dns-change-new.controller.js
Labels: 🐞 bug
