Repository vinyldns/vinyldns, pull requests merged in 2022-11, with the labels that each got.

#1168 Remove 'Complete' zone change status
  modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
  modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneChange.scala
  modules/core/src/test/scala/vinyldns/core/TestZoneData.scala
  modules/core/src/test/scala/vinyldns/core/domain/zone/ZoneChangeSpec.scala
  modules/core/src/test/scala/vinyldns/core/protobuf/ProtobufConversionsSpec.scala
Labels: kind/maintenance

#1171 Override ZoneConnection toString
  modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
  modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
Labels: kind/maintenance

#1172 Correctly handle SPF record data
  modules/api/src/main/scala/vinyldns/api/backend/dns/DnsConversions.scala
  modules/api/src/test/functional/tests/recordsets/create_recordset_test.py
  modules/api/src/test/scala/vinyldns/api/backend/dns/DnsConversionsSpec.scala
Labels: kind/bug

#1170 Remove keys from User by overriding 'toString'
  modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
  modules/core/src/main/scala/vinyldns/core/domain/membership/User.scala
  modules/portal/test/controllers/TestApplicationData.scala
Labels: kind/maintenance

#1166 Add auth on POST /status
  modules/api/src/main/scala/vinyldns/api/route/StatusRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
  modules/api/src/test/functional/tests/internal/status_test.py
  modules/api/src/test/functional/tests/shared_zone_test_context.py
  modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
  modules/api/src/test/scala/vinyldns/api/route/StatusRoutingSpec.scala
Labels: area/api

#1162 Allow All Users to View Any Shared Zone
  modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidations.scala
  modules/api/src/test/functional/tests/zones/get_zone_test.py
  modules/api/src/test/functional/tests/zones/list_zones_test.py
  modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
  modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
  modules/portal/public/lib/controllers/controller.records.js
  modules/portal/public/templates/record-modal.html
Labels: kind/enhancement, area/portal, area/api

#1165 Replaced orchard CIDR library to IP4s library
  build.sbt
  modules/api/src/main/scala/vinyldns/api/config/HighValueDomainConfig.scala
  modules/api/src/main/scala/vinyldns/api/config/ManualReviewConfig.scala
  modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
  modules/api/src/main/scala/vinyldns/api/domain/zone/AclRuleOrdering.scala
  modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRecordValidations.scala
  modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneValidations.scala
  modules/api/src/test/functional/tests/batch/create_batch_change_test.py
  modules/api/src/test/functional/tests/recordsets/create_recordset_test.py
  modules/api/src/test/functional/tests/zones/update_zone_test.py
  modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
  modules/api/src/test/scala/vinyldns/api/domain/ReverseZoneHelpersSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
  project/Dependencies.scala
Labels: help wanted, kind/maintenance

#1167 Replace await with IO
  modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
  modules/api/src/test/scala/vinyldns/api/CatsHelpers.scala
  modules/api/src/test/scala/vinyldns/api/ResultHelpers.scala
  modules/api/src/test/scala/vinyldns/api/domain/auth/MembershipAuthPrincipalProviderSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInterfacesSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/engine/BatchChangeHandlerSpec.scala
  modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
Labels: kind/maintenance
