Repository vinyldns/vinyldns, pull requests merged in 2022-02, with the labels that each got.

#1053 Add the ability to search groups
  modules/portal/app/views/groups/groups.scala.html
  modules/portal/public/lib/controllers/controller.groups.js
  modules/portal/public/lib/services/groups/service.groups.js
Labels: kind/enhancement, status/ready, area/portal

#1082 Fix issues pertaining to running env
  .gitignore
  build/sbt.sh
  modules/api/src/it/scala/vinyldns/api/notifier/sns/SnsNotifierIntegrationSpec.scala
  quickstart/.env
  quickstart/docker-compose.yml
  quickstart/quickstart-vinyldns.sh
Labels: kind/maintenance, area/core

#1081 Maintain atomicity in membership service
  modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
  modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
  modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
  modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
  modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
  modules/api/src/test/scala/vinyldns/api/repository/TestDataLoaderSpec.scala
  modules/core/src/main/scala/vinyldns/core/domain/membership/GroupChangeRepository.scala
  modules/core/src/main/scala/vinyldns/core/domain/membership/GroupRepository.scala
  modules/core/src/main/scala/vinyldns/core/domain/membership/MembershipRepository.scala
  modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlGroupChangeRepositoryIntegrationSpec.scala
  modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlGroupRepositoryIntegrationSpec.scala
  modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlMembershipRepositoryIntegrationSpec.scala
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupChangeRepository.scala
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlMembershipRepository.scala
Labels: kind/maintenance, area/db

#1052 Hardcoded limits changed as configurable.
  modules/api/src/main/resources/reference.conf
  modules/api/src/main/scala/vinyldns/api/Boot.scala
  modules/api/src/main/scala/vinyldns/api/config/LimitsConfig.scala
  modules/api/src/main/scala/vinyldns/api/config/VinylDNSConfig.scala
  modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
  modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
  modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
  modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
  modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/VinylDNSDirectivesSpec.scala
  modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
  modules/docs/src/main/mdoc/operator/config-api.md
Labels: kind/maintenance, status/ready, area/api

#1091 Resolve SQL injection vulnerability
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
Labels: kind/bug, area/api

#1054 Recordset data
  modules/api/src/it/scala/vinyldns/api/route53/Route53ApiIntegrationSpec.scala
  modules/api/src/main/scala/vinyldns/api/Boot.scala
  modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
  modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
  modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
  modules/api/src/main/scala/vinyldns/api/engine/ZoneChangeHandler.scala
  modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
  modules/api/src/main/scala/vinyldns/api/repository/ApiDataAccessor.scala
  modules/api/src/main/scala/vinyldns/api/repository/ApiDataAccessorProvider.scala
  modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
  modules/api/src/test/scala/vinyldns/api/config/VinylDNSConfigSpec.scala
  modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneViewLoaderSpec.scala
  modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
  modules/api/src/test/scala/vinyldns/api/engine/ZoneChangeHandlerSpec.scala
  modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
  modules/api/src/test/scala/vinyldns/api/repository/ApiDataAccessorProviderSpec.scala
  modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
  modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetDataRepository.scala
  modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetRepository.scala
  modules/core/src/main/scala/vinyldns/core/repository/DataStore.scala
  modules/core/src/main/scala/vinyldns/core/repository/DataStoreConfig.scala
  modules/core/src/main/scala/vinyldns/core/repository/Repository.scala
  modules/core/src/test/scala/vinyldns/core/repository/DataStoreLoaderSpec.scala
  modules/core/src/test/scala/vinyldns/core/repository/MockDataStoreProvider.scala
  modules/mysql/src/it/scala/vinyldns/mysql/MySqlIntegrationSpec.scala
  modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepositoryIntegrationSpec.scala
  modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
  modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
  modules/mysql/src/main/resources/test/ddl.sql
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
  modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
Labels: kind/enhancement, status/ready, area/db
